import Head from 'next/head'

import React from 'react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <p className='bg-400 p-10 border border-solid rounded-full'>
        GELU IS BOMBA CU CEAS ALEX TRAGE PE NAS
      </p>
    </div>
  )
}
